### PR TITLE
MTDieTest: Find a bug preventing router from dying

### PR DESCRIPTION
**Pull request by tbarbette**
!This patch does not contain the fix! (as travis tells you)

It appears that from time to time, one of the last threads sleep for an infinite amount of time in select_poll, but it should not do that as the router is dying.. Or maybe it should as at that point the router is not dying, and other threads should then interrupt the polling one...? The result is that the main thread stays in thread_join forever.

The added testie will hit the bug most of the time.

Dying is not the part of Click I know the best... Any idea of fix someone?

### CODE REVIEW

**Comment by tbarbette** [comment]
Poke @rtshanks @sdarayan

**Comment by kohler** [comment]
Please see branch kohler/mtdie, which I believe fixes this issue?

**Comment by kohler** [comment]
FYI I probably won't merge mtdie until I hear back from somebody!

**Comment by kohler** [comment]
Clang builds on travis aren't working on my branch, but it's not clear to me why.

**Comment by tbarbette** [comment]
The test effectively fails once every ten run I'd say on my machine. The router seems to die too soon now...

while true ; do ./test/testie --show-all -p ./bin -p ./test CLICKPATH="`cd .; pwd`:" CLICKTEST_PREINSTALL=1 ./test/threads/MTDieTest-01.testie || break ; done 

Will ultimately stop... I'm looking at it now.

**Comment by tbarbette** [comment]
Only advance I had until now is that if I insert "print" between the wait in the testie, it does not die sooner anymore... Tried a few things but still clueless...

**Comment by kohler** [comment]
I'm going to close this and declare victory. Relevant commits include d8b39ad0a5015e3bb1ba55f24c69910e709ac5f9, 30c52d1dc751b11a03e5fbeb982c4f4e6c5a9710, 0be6b1471176d8f0d8c2f01579ba8486d14bd638. I ran many tens of MTDieTest tests on a multicore and saw no premature exits; Travis is happy. Thanks for the test!

**Pull request closed without merging**
