### PR TITLE
Solve testie issue

### PR DESCRIPTION
**Pull request by tbarbette**
Travis was hitting that from time to time.

This may uncover a new bug related to the "dying router" problem, or perhaps it just always worked by chance until now? So I prefer to push this through a PR for discussion.

### CODE REVIEW

**Comment by kohler** [comment]
Hm. I think the expected behavior is that after the `write hotconfig` completes, the old router is no longer interesting, so the old router's stopping doesn't affect the driver overall. Can you explain what “hitting that” meant? What was the bad behavior?

**Comment by tbarbette** [comment]
Well, I was writing a long answer and sweating because I could not reproduce locally but master is failing on that exact problem ... https://travis-ci.org/kohler/click/jobs/200372194

**Comment by kohler** [comment]
Since I merged a hopefully-fix for the “dying router” problem maybe we're ok now?

**Comment by tbarbette** [comment]
Yes it is probably related. We'll reopen if travis is sad again.

**Pull request closed without merging**
