### PR TITLE
HashTable division (is expensive)

### PR DESCRIPTION
**Pull request by pallas**

### CODE REVIEW

**Comment by pallas** [comment]
Hey, @tbarbette!!

**Comment by tbarbette** [comment]
Nice ! Thanks for the posterity ^^ I imagine there are other place we could use libdivide.

**Comment by pallas** [comment]
I think that's probably correct, and am investigating. This was just the big one..

**Comment by kohler** [comment]
Iiiiiiiiiiiintereeeeeeesting, and in it goes!

**Comment by kohler** [comment]
Thanks much guys!

I have some comments on the size stuff, though. Will add a commit there.

**Comment by kohler** [comment]
Please see commit cbc3675 @tbarbette @pallas

**Pull request merged**
