### PR TITLE
rename testie to clicktest

### PR DESCRIPTION
**Pull request by trackpick**
The naming of Click test scripts and files (testies) has come up a bunch of times as being less than desirable in a diverse workplace and we'd like to rename both.

### CODE REVIEW

**Comment by pallas** [comment]
100% this

**Comment by tbarbette** [comment]
@kohler shall I merge this?

**Comment by kohler** [comment]
FWIW, the name was a diminutive (“a little test”), not a vulgarity, but I agree that the other interpretation sucks.

**Comment by trackpick** [comment]
Thanks =)

**Pull request merged**
